version: '3.8'

services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:debug reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:debug auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
      - '9230:9229'
    volumes:
      - .:/usr/src/app
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
#  mongodb:
#    image: mongo:6
#    container_name: mongodb
#    ports:
#      - "${MONGO_PORT:-27017}:27017"
#    volumes:
#      - ./mongo-data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}