#apiVersion: cloud.google.com/v1
#kind: BackendConfig
#metadata:
#  name: auth-backendconfig
#spec:
#  healthCheck:
#    type: HTTP
#    port: 3003
#    requestPath: /health
#    checkIntervalSec: 10
#    timeoutSec: 5
#    healthyThreshold: 1
#    unhealthyThreshold: 3