apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth-http
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 3003
  selector:
    app: auth
  type: NodePort
