services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    image: us-east4-docker.pkg.dev/boxwood-diagram-469015-a2/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: us-east4-docker.pkg.dev/boxwood-diagram-469015-a2/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: us-east4-docker.pkg.dev/boxwood-diagram-469015-a2/payments/production
    env_file:
      - ../apps/payments/.env
  notifications:
    image: us-east4-docker.pkg.dev/boxwood-diagram-469015-a2/notifications/production
    env_file:
      - ../apps/notifications/.env
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - ../mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}