apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
      - image: us-east4-docker.pkg.dev/boxwood-diagram-469015-a2/reservations/production
#      - image: nginxdemos/hello
        name: reservations
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: ConnectionString
        - name: HTTP_PORT
          value: '3004'
        - name: AUTH_HOST
          value: auth-tcp
        - name: AUTH_PORT
          value: '3002'
        - name: PAYMENTS_HOST
          value: payments
        - name: PAYMENTS_PORT
          value: '3001'
        ports:
        - containerPort: 3004
#          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5